FROM golang:1.23
ENV DEBIAN_FRONTEND noninteractive
ENV ENVIRONMENT=development

# Update and install necessary packages
RUN apt-get update && apt-get install -y \
    ca-certificates \
    poppler-utils  # This installs pdftotext among other utilities

RUN wget https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-linux-amd64-v0.6.1.tar.gz && \
    tar -C /usr/local/bin -xzvf dockerize-linux-amd64-v0.6.1.tar.gz

EXPOSE 80
